version: 'latest'

services:
  app:
     build: ./
     ports:
       - '8080:8080'
     container_name: vktestapp
     restart: unless-stopped
     depends_on:
       - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres